# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chatty(2)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  target 'Chatty(2)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Chatty(2)UITests' do
    # Pods for testing
  end

end
